-- Auto-generated icon mappings from lineageclassic.plaync.com
-- Total: 381 items

UPDATE item_master SET icon_id = '51' WHERE name = '가죽 갑옷';
UPDATE item_master SET icon_id = '451' WHERE name = '가죽모자';
UPDATE item_master SET icon_id = '449' WHERE name = '가죽방패';
UPDATE item_master SET icon_id = '461' WHERE name = '가죽부츠';
UPDATE item_master SET icon_id = '452' WHERE name = '가죽샌달';
UPDATE item_master SET icon_id = '459' WHERE name = '가죽조끼';
UPDATE item_master SET icon_id = '456' WHERE name = '가죽투구';
UPDATE item_master SET icon_id = '261' WHERE name = '간디의 토템';
UPDATE item_master SET icon_id = '467' WHERE name = '갑옷 마법 주문서';
UPDATE item_master SET icon_id = '507' WHERE name = '강철 면갑';
UPDATE item_master SET icon_id = '508' WHERE name = '강철 방패';
UPDATE item_master SET icon_id = '509' WHERE name = '강철 부츠';
UPDATE item_master SET icon_id = '506' WHERE name = '강철 장갑';
UPDATE item_master SET icon_id = '510' WHERE name = '강철 판금 갑옷';
UPDATE item_master SET icon_id = '621' WHERE name = '강화 초록 물약';
UPDATE item_master SET icon_id = '237' WHERE name = '고급 다이아몬드';
UPDATE item_master SET icon_id = '243' WHERE name = '고급 루비';
UPDATE item_master SET icon_id = '246' WHERE name = '고급 사파이어';
UPDATE item_master SET icon_id = '240' WHERE name = '고급 에메랄드';
UPDATE item_master SET icon_id = '455' WHERE name = '고급피혁';
UPDATE item_master SET icon_id = '124' WHERE name = '고기';
UPDATE item_master SET icon_id = '86' WHERE name = '고리 갑옷';
UPDATE item_master SET icon_id = '457' WHERE name = '골각방패';
UPDATE item_master SET icon_id = '439' WHERE name = '광전사의 도끼';
UPDATE item_master SET icon_id = '124' WHERE name = '괴물 눈 고기';
UPDATE item_master SET icon_id = '941' WHERE name = '군주의 위엄';
UPDATE item_master SET icon_id = '48' WHERE name = '귀사름';
UPDATE item_master SET icon_id = '474' WHERE name = '귀환 주문서';
UPDATE item_master SET icon_id = '151' WHERE name = '그라디우스';
UPDATE item_master SET icon_id = '138' WHERE name = '글루디오 영지행 배표';
UPDATE item_master SET icon_id = '59' WHERE name = '금빛 열쇠';
UPDATE item_master SET icon_id = '60' WHERE name = '기병창';
UPDATE item_master SET icon_id = '166' WHERE name = '기사의 면갑';
UPDATE item_master SET icon_id = '252' WHERE name = '기술서 (리덕션 아머)';
UPDATE item_master SET icon_id = '252' WHERE name = '기술서 (바운스 어택)';
UPDATE item_master SET icon_id = '252' WHERE name = '기술서 (쇼크 스턴)';
UPDATE item_master SET icon_id = '109' WHERE name = '나무 갑옷';
UPDATE item_master SET icon_id = '51' WHERE name = '나무 줄기 옷';
UPDATE item_master SET icon_id = '97' WHERE name = '나무방패';
UPDATE item_master SET icon_id = '103' WHERE name = '난쟁이족 검';
UPDATE item_master SET icon_id = '172' WHERE name = '난쟁이족 도끼';
UPDATE item_master SET icon_id = '95' WHERE name = '난쟁이족 둥근 방패';
UPDATE item_master SET icon_id = '27' WHERE name = '난쟁이족 망토';
UPDATE item_master SET icon_id = '52' WHERE name = '난쟁이족 철 투구';
UPDATE item_master SET icon_id = '631' WHERE name = '낡은 신체의 벨트';
UPDATE item_master SET icon_id = '633' WHERE name = '낡은 영혼의 벨트';
UPDATE item_master SET icon_id = '632' WHERE name = '낡은 정신의 벨트';
UPDATE item_master SET icon_id = '21' WHERE name = '넓은 검';
UPDATE item_master SET icon_id = '45' WHERE name = '넓은 창';
UPDATE item_master SET icon_id = '259' WHERE name = '네루가의 토템';
UPDATE item_master SET icon_id = '298' WHERE name = '다마스커스 검';
UPDATE item_master SET icon_id = '236' WHERE name = '다이아몬드';
UPDATE item_master SET icon_id = '322' WHERE name = '단검신';
UPDATE item_master SET icon_id = '116' WHERE name = '단풍나무 막대';
UPDATE item_master SET icon_id = '40' WHERE name = '달걀';
UPDATE item_master SET icon_id = '25' WHERE name = '당근';
UPDATE item_master SET icon_id = '171' WHERE name = '대형 도끼';
UPDATE item_master SET icon_id = '695' WHERE name = '데스나이트의 갑옷';
UPDATE item_master SET icon_id = '701' WHERE name = '데스나이트의 부츠';
UPDATE item_master SET icon_id = '708' WHERE name = '데스나이트의 장갑';
UPDATE item_master SET icon_id = '713' WHERE name = '데스나이트의 투구';
UPDATE item_master SET icon_id = '1' WHERE name = '도끼';
UPDATE item_master SET icon_id = '42' WHERE name = '도리깨';
UPDATE item_master SET icon_id = '446' WHERE name = '동물가죽';
UPDATE item_master SET icon_id = '260' WHERE name = '두다-마라의 토템';
UPDATE item_master SET icon_id = '3' WHERE name = '등잔';
UPDATE item_master SET icon_id = '10' WHERE name = '띠 갑옷';
UPDATE item_master SET icon_id = '140' WHERE name = '랜턴';
UPDATE item_master SET icon_id = '142' WHERE name = '랜턴용 기름';
UPDATE item_master SET icon_id = '63' WHERE name = '레몬';
UPDATE item_master SET icon_id = '104' WHERE name = '레이피어';
UPDATE item_master SET icon_id = '262' WHERE name = '로바의 토템';
UPDATE item_master SET icon_id = '242' WHERE name = '루비';
UPDATE item_master SET icon_id = '66' WHERE name = '루선해머';
UPDATE item_master SET icon_id = '1007' WHERE name = '마나 망토';
UPDATE item_master SET icon_id = '293' WHERE name = '마나의 지팡이';
UPDATE item_master SET icon_id = '906' WHERE name = '마력서';
UPDATE item_master SET icon_id = '235' WHERE name = '마력의 돌';
UPDATE item_master SET icon_id = '292' WHERE name = '마력의 지팡이';
UPDATE item_master SET icon_id = '265' WHERE name = '마법 망토';
UPDATE item_master SET icon_id = '526' WHERE name = '마법사 모자';
UPDATE item_master SET icon_id = '527' WHERE name = '마법사 옷';
UPDATE item_master SET icon_id = '297' WHERE name = '마법사의 지팡이';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (그레이터 헤이스트)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (그레이터 힐)';
UPDATE item_master SET icon_id = '255' WHERE name = '마법서 (다크니스)';
UPDATE item_master SET icon_id = '256' WHERE name = '마법서 (디지즈)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (디크리즈 웨이트)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (디텍션)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (라이트)';
UPDATE item_master SET icon_id = '252' WHERE name = '마법서 (라이트닝 스톰)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (라이트닝)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (리무브 커스)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (리절렉션)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (마나 드레인)';
UPDATE item_master SET icon_id = '252' WHERE name = '마법서 (매스 텔레포트)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (메디테이션)';
UPDATE item_master SET icon_id = '254' WHERE name = '마법서 (뱀파이어릭 터치)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (버서커스)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (블레스 웨폰)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (블레스드 아머)';
UPDATE item_master SET icon_id = '256' WHERE name = '마법서 (블리자드)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (사일런스)';
UPDATE item_master SET icon_id = '256' WHERE name = '마법서 (서먼 몬스터)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (선 버스트)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (셰이프 체인지)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (스탈락)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (슬로우)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (실드)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (아이스 대거)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (아이스 랜스)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (어스 재일)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (어스 퀘이크)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (에너지 볼트)';
UPDATE item_master SET icon_id = '254' WHERE name = '마법서 (웨폰 브레이크)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (위크 엘리멘탈)';
UPDATE item_master SET icon_id = '255' WHERE name = '마법서 (위크니스)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (윈드 커터)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (이럽션)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (익스트라 힐)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (인비지블리티)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (인챈트 덱스터리티)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (인챈트 마이티)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (인챈트 웨폰)';
UPDATE item_master SET icon_id = '253' WHERE name = '마법서 (칠 터치)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (카운터 디텍션)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (카운터 매직)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (캔슬레이션)';
UPDATE item_master SET icon_id = '254' WHERE name = '마법서 (커스: 블라인드)';
UPDATE item_master SET icon_id = '255' WHERE name = '마법서 (커스: 패럴라이즈)';
UPDATE item_master SET icon_id = '253' WHERE name = '마법서 (커스: 포이즌)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (콘 오브 콜드)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (콜 라이트닝)';
UPDATE item_master SET icon_id = '252' WHERE name = '마법서 (콜 클랜)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (큐어 포이즌)';
UPDATE item_master SET icon_id = '255' WHERE name = '마법서 (크리에이트 좀비)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (턴 언데드)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (테이밍 몬스터)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (텔레포트)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (토네이도)';
UPDATE item_master SET icon_id = '252' WHERE name = '마법서 (트루 타겟)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (파이어 애로우)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (파이어볼)';
UPDATE item_master SET icon_id = '249' WHERE name = '마법서 (프로즌 클라우드)';
UPDATE item_master SET icon_id = '250' WHERE name = '마법서 (헤이스트)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (홀리 워크)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (홀리 웨폰)';
UPDATE item_master SET icon_id = '251' WHERE name = '마법서 (힐 올)';
UPDATE item_master SET icon_id = '248' WHERE name = '마법서 (힐)';
UPDATE item_master SET icon_id = '168' WHERE name = '마법의 투구: 신속';
UPDATE item_master SET icon_id = '167' WHERE name = '마법의 투구: 치유';
UPDATE item_master SET icon_id = '170' WHERE name = '마법의 투구: 힘';
UPDATE item_master SET icon_id = '43' WHERE name = '마법의 플룻';
UPDATE item_master SET icon_id = '138' WHERE name = '말하는 섬행 배표';
UPDATE item_master SET icon_id = '81' WHERE name = '맑은 물약';
UPDATE item_master SET icon_id = '304' WHERE name = '매력의 목걸이';
UPDATE item_master SET icon_id = '1233' WHERE name = '메르키오르의 모자';
UPDATE item_master SET icon_id = '276' WHERE name = '메일 브레이커';
UPDATE item_master SET icon_id = '68' WHERE name = '모닝스타';
UPDATE item_master SET icon_id = '31' WHERE name = '몽둥이';
UPDATE item_master SET icon_id = '468' WHERE name = '무기 마법 주문서';
UPDATE item_master SET icon_id = '287' WHERE name = '무명 로브';
UPDATE item_master SET icon_id = '102' WHERE name = '미늘 갑옷';
UPDATE item_master SET icon_id = '50' WHERE name = '미늘창';
UPDATE item_master SET icon_id = '318' WHERE name = '미스릴';
UPDATE item_master SET icon_id = '315' WHERE name = '미스릴 도금 뿔';
UPDATE item_master SET icon_id = '307' WHERE name = '미스릴 실';
UPDATE item_master SET icon_id = '320' WHERE name = '미스릴 원석';
UPDATE item_master SET icon_id = '329' WHERE name = '미스릴 판금';
UPDATE item_master SET icon_id = '96' WHERE name = '미스릴 화살';
UPDATE item_master SET icon_id = '304' WHERE name = '민첩의 목걸이';
UPDATE item_master SET icon_id = '913' WHERE name = '민첩함의 투구';
UPDATE item_master SET icon_id = '127' WHERE name = '바나나';
UPDATE item_master SET icon_id = '11' WHERE name = '바르디쉐';
UPDATE item_master SET icon_id = '137' WHERE name = '반사 방패';
UPDATE item_master SET icon_id = '1231' WHERE name = '발터자르의 모자';
UPDATE item_master SET icon_id = '82' WHERE name = '버섯포자의 즙';
UPDATE item_master SET icon_id = '38' WHERE name = '벡드코빈';
UPDATE item_master SET icon_id = '264' WHERE name = '벨트';
UPDATE item_master SET icon_id = '460' WHERE name = '벨트달린 가죽조끼';
UPDATE item_master SET icon_id = '87' WHERE name = '변신 조종 반지';
UPDATE item_master SET icon_id = '472' WHERE name = '변신 주문서';
UPDATE item_master SET icon_id = '30' WHERE name = '보호 망토';
UPDATE item_master SET icon_id = '1011' WHERE name = '보호 장갑';
UPDATE item_master SET icon_id = '435' WHERE name = '부츠';
UPDATE item_master SET icon_id = '471' WHERE name = '부활 주문서';
UPDATE item_master SET icon_id = '82' WHERE name = '불투명 물약';
UPDATE item_master SET icon_id = '441' WHERE name = '붉은 기사의 검';
UPDATE item_master SET icon_id = '916' WHERE name = '붉은 기사의 두건';
UPDATE item_master SET icon_id = '954' WHERE name = '붉은 기사의 방패';
UPDATE item_master SET icon_id = '907' WHERE name = '붉은 망토';
UPDATE item_master SET icon_id = '519' WHERE name = '붉은 옷감';
UPDATE item_master SET icon_id = '89' WHERE name = '비늘 갑옷';
UPDATE item_master SET icon_id = '76' WHERE name = '비취 물약';
UPDATE item_master SET icon_id = '13' WHERE name = '빌귀사름';
UPDATE item_master SET icon_id = '1171' WHERE name = '빛나는 비늘';
UPDATE item_master SET icon_id = '1168' WHERE name = '빛나는 신체의 벨트';
UPDATE item_master SET icon_id = '1170' WHERE name = '빛나는 영혼의 벨트';
UPDATE item_master SET icon_id = '1169' WHERE name = '빛나는 정신의 벨트';
UPDATE item_master SET icon_id = '80' WHERE name = '빨간 물약';
UPDATE item_master SET icon_id = '448' WHERE name = '뼈갑옷';
UPDATE item_master SET icon_id = '444' WHERE name = '뼈조각';
UPDATE item_master SET icon_id = '177' WHERE name = '사각 방패';
UPDATE item_master SET icon_id = '995' WHERE name = '사과';
UPDATE item_master SET icon_id = '279' WHERE name = '사냥꾼 활';
UPDATE item_master SET icon_id = '1201' WHERE name = '사슬 갑옷';
UPDATE item_master SET icon_id = '488' WHERE name = '사탕';
UPDATE item_master SET icon_id = '245' WHERE name = '사파이어';
UPDATE item_master SET icon_id = '111' WHERE name = '삼지창';
UPDATE item_master SET icon_id = '1234' WHERE name = '세마의 모자';
UPDATE item_master SET icon_id = '117' WHERE name = '소나무 막대';
UPDATE item_master SET icon_id = '20044' WHERE name = '속죄의 성서 상자';
UPDATE item_master SET icon_id = '547' WHERE name = '수룡 비늘';
UPDATE item_master SET icon_id = '539' WHERE name = '수룡 비늘 갑옷';
UPDATE item_master SET icon_id = '32' WHERE name = '수정 갑옷';
UPDATE item_master SET icon_id = '939' WHERE name = '수정 지팡이';
UPDATE item_master SET icon_id = '704' WHERE name = '수중 부츠';
UPDATE item_master SET icon_id = '20138' WHERE name = '수호의 목걸이';
UPDATE item_master SET icon_id = '20025' WHERE name = '수호의 반지';
UPDATE item_master SET icon_id = '905' WHERE name = '수호자의 반지';
UPDATE item_master SET icon_id = '87' WHERE name = '순간이동 조종 반지';
UPDATE item_master SET icon_id = '473' WHERE name = '순간이동 주문서';
UPDATE item_master SET icon_id = '478' WHERE name = '숫돌';
UPDATE item_master SET icon_id = '634' WHERE name = '신체의 벨트';
UPDATE item_master SET icon_id = '326' WHERE name = '실';
UPDATE item_master SET icon_id = '5' WHERE name = '아데나';
UPDATE item_master SET icon_id = '308' WHERE name = '아라크네의 거미줄';
UPDATE item_master SET icon_id = '306' WHERE name = '아라크네의 허물';
UPDATE item_master SET icon_id = '8' WHERE name = '아탐';
UPDATE item_master SET icon_id = '258' WHERE name = '아투바의 토템';
UPDATE item_master SET icon_id = '20029' WHERE name = '악마의 피';
UPDATE item_master SET icon_id = '144' WHERE name = '악운의 단검';
UPDATE item_master SET icon_id = '4' WHERE name = '양손검';
UPDATE item_master SET icon_id = '24' WHERE name = '양초';
UPDATE item_master SET icon_id = '90' WHERE name = '언월도';
UPDATE item_master SET icon_id = '239' WHERE name = '에메랄드';
UPDATE item_master SET icon_id = '1203' WHERE name = '에바의 방패';
UPDATE item_master SET icon_id = '557' WHERE name = '에바의 축복';
UPDATE item_master SET icon_id = '311' WHERE name = '엔트의 껍질';
UPDATE item_master SET icon_id = '126' WHERE name = '엔트의 열매';
UPDATE item_master SET icon_id = '309' WHERE name = '엔트의 줄기';
UPDATE item_master SET icon_id = '267' WHERE name = '엘름의 축복';
UPDATE item_master SET icon_id = '130' WHERE name = '엘븐 와퍼';
UPDATE item_master SET icon_id = '636' WHERE name = '영혼의 벨트';
UPDATE item_master SET icon_id = '71' WHERE name = '오렌지';
UPDATE item_master SET icon_id = '319' WHERE name = '오리하루콘';
UPDATE item_master SET icon_id = '321' WHERE name = '오리하루콘 검신';
UPDATE item_master SET icon_id = '316' WHERE name = '오리하루콘 도금 뿔';
UPDATE item_master SET icon_id = '330' WHERE name = '오리하루콘 판금';
UPDATE item_master SET icon_id = '697' WHERE name = '오우거의 벨트';
UPDATE item_master SET icon_id = '324' WHERE name = '오우거의 피';
UPDATE item_master SET icon_id = '436' WHERE name = '오크 투사의 목걸이';
UPDATE item_master SET icon_id = '105' WHERE name = '오크족 검';
UPDATE item_master SET icon_id = '442' WHERE name = '오크족 고리 갑옷';
UPDATE item_master SET icon_id = '34' WHERE name = '오크족 단검';
UPDATE item_master SET icon_id = '29' WHERE name = '오크족 망토';
UPDATE item_master SET icon_id = '443' WHERE name = '오크족 사슬 갑옷';
UPDATE item_master SET icon_id = '100' WHERE name = '오크족 창';
UPDATE item_master SET icon_id = '54' WHERE name = '오크족 투구';
UPDATE item_master SET icon_id = '19' WHERE name = '오크족 활';
UPDATE item_master SET icon_id = '304' WHERE name = '완력의 목걸이';
UPDATE item_master SET icon_id = '53' WHERE name = '요정족 가죽 투구';
UPDATE item_master SET icon_id = '325' WHERE name = '요정족 검';
UPDATE item_master SET icon_id = '33' WHERE name = '요정족 단검';
UPDATE item_master SET icon_id = '28' WHERE name = '요정족 망토';
UPDATE item_master SET icon_id = '92' WHERE name = '요정족 방패';
UPDATE item_master SET icon_id = '281' WHERE name = '요정족 사슬 갑옷';
UPDATE item_master SET icon_id = '99' WHERE name = '요정족 창';
UPDATE item_master SET icon_id = '956' WHERE name = '요정족 티셔츠';
UPDATE item_master SET icon_id = '275' WHERE name = '요정족 판금 갑옷';
UPDATE item_master SET icon_id = '18' WHERE name = '요정족 활';
UPDATE item_master SET icon_id = '302' WHERE name = '요정족 흉갑';
UPDATE item_master SET icon_id = '79' WHERE name = '용기의 물약';
UPDATE item_master SET icon_id = '1009' WHERE name = '용기의 벨트';
UPDATE item_master SET icon_id = '114' WHERE name = '우럭하이 방패';
UPDATE item_master SET icon_id = '119' WHERE name = '워해머';
UPDATE item_master SET icon_id = '96' WHERE name = '은 화살';
UPDATE item_master SET icon_id = '156' WHERE name = '은검';
UPDATE item_master SET icon_id = '332' WHERE name = '은기사의 방패';
UPDATE item_master SET icon_id = '173' WHERE name = '은도끼';
UPDATE item_master SET icon_id = '163' WHERE name = '은장검';
UPDATE item_master SET icon_id = '59' WHERE name = '은회색 열쇠';
UPDATE item_master SET icon_id = '556' WHERE name = '인어의 비늘';
UPDATE item_master SET icon_id = '58' WHERE name = '일본도';
UPDATE item_master SET icon_id = '97' WHERE name = '작은 방패';
UPDATE item_master SET icon_id = '141' WHERE name = '장갑';
UPDATE item_master SET icon_id = '2' WHERE name = '장검';
UPDATE item_master SET icon_id = '321' WHERE name = '장검신';
UPDATE item_master SET icon_id = '123' WHERE name = '장궁';
UPDATE item_master SET icon_id = '470' WHERE name = '저주 풀기 주문서';
UPDATE item_master SET icon_id = '9' WHERE name = '전투 도끼';
UPDATE item_master SET icon_id = '706' WHERE name = '정령옥';
UPDATE item_master SET icon_id = '235' WHERE name = '정령의 돌';
UPDATE item_master SET icon_id = '688' WHERE name = '정령의 수정 (네이쳐스 블레싱)';
UPDATE item_master SET icon_id = '683' WHERE name = '정령의 수정 (네이쳐스 터치)';
UPDATE item_master SET icon_id = '673' WHERE name = '정령의 수정 (레지스트 매직)';
UPDATE item_master SET icon_id = '674' WHERE name = '정령의 수정 (레지스트 엘리멘트)';
UPDATE item_master SET icon_id = '677' WHERE name = '정령의 수정 (리턴 투 네이처)';
UPDATE item_master SET icon_id = '673' WHERE name = '정령의 수정 (바디 투 마인드)';
UPDATE item_master SET icon_id = '680' WHERE name = '정령의 수정 (브레스 오브 파이어)';
UPDATE item_master SET icon_id = '677' WHERE name = '정령의 수정 (블러드 투 소울)';
UPDATE item_master SET icon_id = '681' WHERE name = '정령의 수정 (블레스 오브 어스)';
UPDATE item_master SET icon_id = '682' WHERE name = '정령의 수정 (서먼 레서 엘리멘탈)';
UPDATE item_master SET icon_id = '684' WHERE name = '정령의 수정 (아이 오브 스톰)';
UPDATE item_master SET icon_id = '681' WHERE name = '정령의 수정 (어스 바인드)';
UPDATE item_master SET icon_id = '676' WHERE name = '정령의 수정 (어스 스킨)';
UPDATE item_master SET icon_id = '679' WHERE name = '정령의 수정 (윈드 샷)';
UPDATE item_master SET icon_id = '679' WHERE name = '정령의 수정 (윈드 워크)';
UPDATE item_master SET icon_id = '682' WHERE name = '정령의 수정 (이레이즈 매직)';
UPDATE item_master SET icon_id = '676' WHERE name = '정령의 수정 (인탱글)';
UPDATE item_master SET icon_id = '674' WHERE name = '정령의 수정 (클리어 마인드)';
UPDATE item_master SET icon_id = '673' WHERE name = '정령의 수정 (텔레포트 투 마더)';
UPDATE item_master SET icon_id = '677' WHERE name = '정령의 수정 (트리플 애로우)';
UPDATE item_master SET icon_id = '675' WHERE name = '정령의 수정 (파이어 웨폰)';
UPDATE item_master SET icon_id = '677' WHERE name = '정령의 수정 (프로텍션 프롬 엘리멘트)';
UPDATE item_master SET icon_id = '635' WHERE name = '정신의 벨트';
UPDATE item_master SET icon_id = '78' WHERE name = '주홍 물약';
UPDATE item_master SET icon_id = '462' WHERE name = '중갑가죽조끼';
UPDATE item_master SET icon_id = '548' WHERE name = '지룡 비늘';
UPDATE item_master SET icon_id = '540' WHERE name = '지룡 비늘 갑옷';
UPDATE item_master SET icon_id = '304' WHERE name = '지식의 목걸이';
UPDATE item_master SET icon_id = '304' WHERE name = '지혜의 목걸이';
UPDATE item_master SET icon_id = '1529' WHERE name = '지혜의 물약';
UPDATE item_master SET icon_id = '445' WHERE name = '징박은 가죽모자';
UPDATE item_master SET icon_id = '450' WHERE name = '징박은 가죽방패';
UPDATE item_master SET icon_id = '447' WHERE name = '징박은 가죽샌달';
UPDATE item_master SET icon_id = '458' WHERE name = '징박은 가죽조끼';
UPDATE item_master SET icon_id = '109' WHERE name = '징박힌 가죽 갑옷';
UPDATE item_master SET icon_id = '106' WHERE name = '짧은 검';
UPDATE item_master SET icon_id = '65' WHERE name = '짧은 부츠';
UPDATE item_master SET icon_id = '291' WHERE name = '참나무 지팡이';
UPDATE item_master SET icon_id = '101' WHERE name = '창';
UPDATE item_master SET icon_id = '454' WHERE name = '철괴';
UPDATE item_master SET icon_id = '67' WHERE name = '철퇴';
UPDATE item_master SET icon_id = '22' WHERE name = '청동 판금 갑옷';
UPDATE item_master SET icon_id = '304' WHERE name = '체력의 목걸이';
UPDATE item_master SET icon_id = '908' WHERE name = '체력의 투구';
UPDATE item_master SET icon_id = '77' WHERE name = '초록 물약';
UPDATE item_master SET icon_id = '238' WHERE name = '최고급 다이아몬드';
UPDATE item_master SET icon_id = '244' WHERE name = '최고급 루비';
UPDATE item_master SET icon_id = '247' WHERE name = '최고급 사파이어';
UPDATE item_master SET icon_id = '241' WHERE name = '최고급 에메랄드';
UPDATE item_master SET icon_id = '1232' WHERE name = '카스파의 모자';
UPDATE item_master SET icon_id = '1246' WHERE name = '커츠의 갑옷';
UPDATE item_master SET icon_id = '1247' WHERE name = '커츠의 부츠';
UPDATE item_master SET icon_id = '1244' WHERE name = '커츠의 장갑';
UPDATE item_master SET icon_id = '1245' WHERE name = '커츠의 투구';
UPDATE item_master SET icon_id = '305' WHERE name = '크로스 보우';
UPDATE item_master SET icon_id = '61' WHERE name = '큰 방패';
UPDATE item_master SET icon_id = '1204' WHERE name = '투구';
UPDATE item_master SET icon_id = '272' WHERE name = '투명 망토';
UPDATE item_master SET icon_id = '699' WHERE name = '트롤의 벨트';
UPDATE item_master SET icon_id = '110' WHERE name = '티셔츠';
UPDATE item_master SET icon_id = '75' WHERE name = '파란 물약';
UPDATE item_master SET icon_id = '517' WHERE name = '파란 옷감';
UPDATE item_master SET icon_id = '72' WHERE name = '파르티잔';
UPDATE item_master SET icon_id = '328' WHERE name = '파워 글로브';
UPDATE item_master SET icon_id = '73' WHERE name = '판금 갑옷';
UPDATE item_master SET icon_id = '314' WHERE name = '판의 갈기털';
UPDATE item_master SET icon_id = '317' WHERE name = '판의 뿔';
UPDATE item_master SET icon_id = '125' WHERE name = '팬케익';
UPDATE item_master SET icon_id = '312' WHERE name = '페어리 더스트';
UPDATE item_master SET icon_id = '313' WHERE name = '페어리의 날개';
UPDATE item_master SET icon_id = '487' WHERE name = '펫 목걸이';
UPDATE item_master SET icon_id = '477' WHERE name = '펫 호루라기';
UPDATE item_master SET icon_id = '464' WHERE name = '편지지';
UPDATE item_master SET icon_id = '41' WHERE name = '포챠드';
UPDATE item_master SET icon_id = '550' WHERE name = '풍룡 비늘';
UPDATE item_master SET icon_id = '520' WHERE name = '하얀 옷감';
UPDATE item_master SET icon_id = '453' WHERE name = '해골투구';
UPDATE item_master SET icon_id = '474' WHERE name = '혈맹 귀환 주문서';
UPDATE item_master SET icon_id = '464' WHERE name = '혈맹 편지지';
UPDATE item_master SET icon_id = '549' WHERE name = '화룡 비늘';
UPDATE item_master SET icon_id = '7' WHERE name = '화살';
UPDATE item_master SET icon_id = '475' WHERE name = '확인 주문서';
UPDATE item_master SET icon_id = '20' WHERE name = '활';
UPDATE item_master SET icon_id = '327' WHERE name = '활 골무';
UPDATE item_master SET icon_id = '118' WHERE name = '흑단 막대';
UPDATE item_master SET icon_id = '1229' WHERE name = '흑장로의 로브';
UPDATE item_master SET icon_id = '1230' WHERE name = '흑장로의 샌달';
UPDATE item_master SET icon_id = '293' WHERE name = '힘의 지팡이';
